app:
  devMode: true

solana:
  network:
    mainnet: "https://api.mainnet-beta.solana.com"
    devnet: "https://api.devnet.solana.com"
    testnet: "https://api.testnet.solana.com"
  public-key: 9LeKjcWCZKCsuMiU34veSWDdb1Vjw2bVhswswWs3D54q

http:
  host: "localhost"
  port: "8082"